security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: foo
      clientSecret: bar
      accessTokenUri: http://localhost:8100/sso-server/oauth/token
      userAuthorizationUri: http://localhost:8100/sso-server/oauth/authorize
    resource:
      userInfoUri: http://localhost:8100/sso-server/user/me

server:
  port: 8110

