server:
  port: 8090

spring:
  security:
    oauth2:
      client:
        registration:
          front:
            authorizationGrantType: authorization_code
            clientId: client_service
            clientSecret: clientsecret
            redirectUriTemplate: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          front:
            token-uri: /auth/oauth/token
            authorizationUri: /auth/oauth/authorize
            user-info-uri: /auth/user/me

zuul:
  routes:
    events:
      path: /events/**
      url: http://lemmeknow.tk:8092/events
    notifications:
      path: /notifications/**
      url: http://lemmeknow.tk:8093/notifications
    parser:
      path: /parser/**
      url: http://lemmeknow.tk:8094/parser
    scheduler:
      path: /scheduler/**
      url: http://lemmeknow.tk:8095/scheduler
    security:
      path: /auth/**
      url: http://lemmeknow.tk:9999/auth


#security:
#  oauth2:
#    client:
#      client-id: notification_service
#      client-secret: pin
#      accessTokenUri: http://localhost:9999/auth/oauth/token
#      userAuthorizationUri: http://localhost:9999/auth/oauth/authorize
##      registered-redirect-uri: http://localhost:8090
#    resource:
#      user-info-uri: http://localhost:9999/auth/user/me
